---
version: "3.7"

# This docker-compose file is used to build and test the container

secrets:
  quote_txt:
    file: ./src/secrets/quote.txt

services:
  pca-report-library:
    # Run the container normally
    build:
      # VERSION must be specified on the command line:
      # e.g., --build-arg VERSION=0.0.1
      context: .
      dockerfile: Dockerfile
    image: cisagov/pca-report-library
    init: true
    restart: "no"

  pca-report-library-version:
    # Run the container to collect version information
    image: cisagov/pca-report-library
    init: true
    restart: "no"
    command: --version
